# Use Node.js 14 LTS as base image
FROM node:14

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm install

# Bundle app source
COPY . .

# Copy Cliente.html to the app directory inside the container
COPY Cliente.html /usr/src/app/Cliente.html

# Expose port 3000
EXPOSE 3000

# Command to run the app
CMD ["node", "servidor.js"]
