name: Build and Push Docker images
 
on:
  push:
    branches:
      - main
 
jobs:
  build-and-push:
    runs-on: ubuntu-latest
 
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_KEY: ${{ secrets.EC2_KEY }}
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
 
      - name: Login to DockerHub
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
 
      - name: Build and push servicio-categorias
        uses: docker/build-push-action@v2
        with:
          context: ./servicio-categorias
          file: ./servicio-categorias/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/servicio-categorias:latest
 
      - name: Build and push servicio-productos
        uses: docker/build-push-action@v2
        with:
          context: ./servicio-productos
          file: ./servicio-productos/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/servicio-productos:latest
 
      - name: Build and push servicio-usuarios
        uses: docker/build-push-action@v2
        with:
          context: ./servicio-usuarios
          file: ./servicio-usuarios/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/servicio-usuarios:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}  
          script: |
            docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
            docker pull ${{ secrets.DOCKER_USERNAME }}/servicio-categorias:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/servicio-productos:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/servicio-usuarios:latest
            docker stop servicio-categoria || true
            docker stop servicio-productos || true
            docker stop servicio-usuarios || true
            docker rm servicio-categoria || true
            docker rm servicio-productos || true
            docker rm servicio-usuarios || true
            docker run -d --name servicio-categoria -p 4001:4001 ${{ secrets.DOCKER_USERNAME }}/servicio-categorias:latest
            docker run -d --name servicio-productos -p 4003:4003 ${{ secrets.DOCKER_USERNAME }}/servicio-productos:latest
            docker run -d --name servicio-usuarios -p 4002:4002 ${{ secrets.DOCKER_USERNAME }}/servicio-usuarios:latest
